language: node_js
node_js:
  - 'lts/*'
os:
  - linux
  - osx
  - windows
cache:
  yarn: true
  directories:
    - 'node_modules'
    - 'dist'
    - 'coverage'
script:
  - yarn build
  - yarn test
  - yarn test:ci
after_script:
  - cat ./coverage/lcov.info | coveralls
