language: node_js
node_js:
  - 'lts/*'
services:
  - docker
before_install:
  docker-compose -f docker-compose.dev.yml up -d
cache:
  yarn: true
  directories:
    - 'node_modules'
script:
  - yarn test
  - yarn test:ci
