version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"
  postgres:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
    volumes:
        - ./data/postgres:/data/postgres
    ports:
      - "5432:5432"
  api:
    container_name: api-container
    image: node:12
    working_dir: /usr/src/cadastro-ferramentas
    restart: always
    command: bash -c "yarn --only=prod && yarn debug"
    environment:
      - MONGO_URL=mongodb://mongo:27017/cadastro-ferramentas
      - DB_HOST=postgres
      - DB_USERNAME=POSTGRES_USER
      - DB_PASSWORD=POSTGRES_PASSWORD
    volumes:
      - ./dist/:/usr/src/cadastro-ferramentas/dist/
      - ./package.json:/usr/src/cadastro-ferramentas/package.json
    ports:
      - "3333:3333"
      - "9222:9222"
    links:
      - mongo
      - postgres
