version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:12
    working_dir: /usr/src/cadastro-ferramentas
    restart: always
    command: bash -c "yarn --only=prod && yarn debug"
    environment:
      - MONGO_URL=mongodb://mongo:27017/cadastro-ferramentas
    volumes:
      - ./dist/:/usr/src/cadastro-ferramentas/dist/
      - ./package.json:/usr/src/cadastro-ferramentas/package.json
    ports:
      - "3333:3333"
      - "9222:9222"
    links:
      - mongo
